[package]
name = "tcode-web"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
gpui_platform = { git = "https://github.com/zed-industries/zed" }
gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "031555662e99a1b5a549990b47f246d475b8288a" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "031555662e99a1b5a549990b47f246d475b8288a" }
client-app = { path = "../client-app" }
js-sys = "0.3"
sync-client = { path = "../sync-client" }
sync-protocol = { path = "../sync-protocol" }
tcode-ui = { path = "../ui", default-features = false, features = ["portable"] }
wasm-bindgen = "0.2"

[target.'cfg(target_arch = "wasm32")'.dependencies.web-sys]
version = "0.3"
features = [
    "CloseEvent",
    "Event",
    "Location",
    "MessageEvent",
    "UrlSearchParams",
    "WebSocket",
    "Window",
]
