mod acp_panel;
mod add_project_dialog;
pub mod assets;
mod attachments;
mod chat;
mod commit_dialog;
mod composer;
mod composer_trigger;
mod context_meter;
mod diff_panel;
pub mod git;
mod highlight;
pub mod markdown;
pub mod material;
mod orchestrate_settings;
mod palette;
mod pasteboard;
mod plan_panel;
mod preview_panel;
pub mod provider_card;
mod provider_dialog;
mod provider_model_picker;
pub mod provider_models;
pub mod provider_status;
pub mod runtime_event;
pub mod settings;
mod settings_page;
mod shell;
mod sidebar;
mod terminal_drawer;
pub mod time;
pub(crate) mod toast;
mod workspace_walk;

pub(crate) use shell::window_drag_area;
pub use shell::{AppShell, Quit, TogglePalette};
