[package]
name = "term"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2"
rio-graphics = "0.5.24"
rio-vt = { version = "0.5.24", features = ["graphics"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
] }
