[package]
name = "tcode-ios"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "tcode_ios"
crate-type = ["staticlib", "rlib"]

[dependencies]
gpui = { package = "gpui-pre", version = "=0.3.3", default-features = false }
gpui-ios = { path = "../platform/gpui-ios" }
log = "0.4"
tcode-mobile = { path = "../mobile" }
tcode-ui = { path = "../ui", default-features = false }
