//! Leaving agents' credits out of the message GitHub would write for a merge or squash.

const AGENT_EMAILS: [&str; 7] = [
    "noreply@anthropic.com",
    "claude@anthropic.com",
    "noreply@openai.com",
    "codex@openai.com",
    "cursoragent@cursor.com",
    "copilot@github.com",
    "noreply@github.com",
];

const AGENT_NAMES: [&str; 9] = [
    "claude code",
    "claude",
    "codex",
    "cursor",
    "github copilot",
    "copilot",
    "opencode",
    "grok",
    "antigravity",
];

const AGENT_SITES: [&str; 9] = [
    "claude.ai",
    "www.anthropic.com",
    "chatgpt.com",
    "openai.com",
    "cursor.com",
    "github.com",
    "opencode.ai",
    "x.ai",
    "antigravity.google",
];

/// The message without standalone agent `Co-authored-by` lines and "Generated with …" footers.
/// People's credits, prose and anything quoted in code stay, and a message with nothing to
/// remove comes back unchanged.
pub fn remove_agent_credits(message: &str) -> String {
    let newline = if message.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    };
    let mut fence: Option<String> = None;
    let mut removed = false;
    let kept: Vec<&str> = message
        .split('\n')
        .map(|line| line.strip_suffix('\r').unwrap_or(line))
        .filter(|line| {
            if line.starts_with("    ") || line.starts_with('\t') {
                return true;
            }
            if let Some((marker, remainder)) = fence_delimiter(line) {
                match &fence {
                    None if marker.starts_with('~') || !remainder.contains('`') => {
                        fence = Some(marker.to_owned());
                    }
                    Some(open)
                        if open.as_bytes()[0] == marker.as_bytes()[0]
                            && marker.len() >= open.len()
                            && remainder.trim_matches([' ', '\t']).is_empty() =>
                    {
                        fence = None;
                    }
                    _ => {}
                }
                return true;
            }
            if fence.is_some() {
                return true;
            }
            let credit = is_agent_author(line) || is_generated_footer(line);
            removed |= credit;
            !credit
        })
        .collect();
    if !removed {
        return message.to_owned();
    }
    let mut text = kept.join(newline);
    // Blank lines the credits leave at the end go with them.
    loop {
        let trimmed = text.trim_end_matches([' ', '\t']);
        let Some(rest) = trimmed.strip_suffix('\n') else {
            break;
        };
        let rest = rest.strip_suffix('\r').unwrap_or(rest).len();
        text.truncate(rest);
    }
    text
}

/// A code fence's marker and what follows it, for a line that opens or closes one.
fn fence_delimiter(line: &str) -> Option<(&str, &str)> {
    let indent = line.len() - line.trim_start_matches(' ').len();
    if indent > 3 {
        return None;
    }
    let rest = &line[indent..];
    let symbol = rest.chars().next().filter(|c| *c == '`' || *c == '~')?;
    let length = rest.len() - rest.trim_start_matches(symbol).len();
    (length >= 3).then(|| rest.split_at(length))
}

/// The line's text without its list marker.
fn credit_text(line: &str) -> &str {
    let text = line.trim();
    match text.strip_prefix(['-', '*']) {
        Some(rest) if rest.starts_with(char::is_whitespace) => rest.trim_start(),
        _ => text,
    }
}

fn is_agent_author(line: &str) -> bool {
    let text = credit_text(line);
    let Some(prefix) = text.get(..15) else {
        return false;
    };
    if !prefix.eq_ignore_ascii_case("co-authored-by:") {
        return false;
    }
    let Some(person) = text[15..].strip_suffix('>') else {
        return false;
    };
    let Some((name, email)) = person.rsplit_once('<') else {
        return false;
    };
    let email = email.to_ascii_lowercase();
    if email.is_empty() || email.contains('>') || !AGENT_EMAILS.contains(&email.as_str()) {
        return false;
    }
    // GitHub's generic noreply address is also people's; only Copilot's name makes it an agent.
    let name = name.trim().to_lowercase();
    email != "noreply@github.com" || name == "github copilot" || name == "copilot"
}

fn is_generated_footer(line: &str) -> bool {
    let footer = unlink_agent_sites(credit_text(line)).to_lowercase();
    let footer = footer
        .strip_prefix('🤖')
        .map_or(footer.as_str(), str::trim_start);
    let Some(rest) = footer
        .strip_prefix("generated with")
        .or_else(|| footer.strip_prefix("generated by"))
    else {
        return false;
    };
    if !rest.starts_with(char::is_whitespace) {
        return false;
    }
    let rest = rest.trim_start();
    let rest = rest
        .strip_suffix(['.', '!'])
        .filter(|name| AGENT_NAMES.contains(name))
        .unwrap_or(rest);
    AGENT_NAMES.contains(&rest)
}

/// Markdown links to an agent's site, reduced to their text.
fn unlink_agent_sites(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(open) = rest.find('[') {
        out.push_str(&rest[..open]);
        let candidate = &rest[open..];
        match agent_link(candidate) {
            Some((label, length)) => {
                out.push_str(label);
                rest = &candidate[length..];
            }
            None => {
                out.push('[');
                rest = &candidate[1..];
            }
        }
    }
    out.push_str(rest);
    out
}

/// The label and length of `[label](https://site/…)` at the start of `text`.
fn agent_link(text: &str) -> Option<(&str, usize)> {
    let close = text.find(']')?;
    let label = &text[1..close];
    if label.is_empty() {
        return None;
    }
    let target = text[close + 1..].strip_prefix("(https://")?;
    let site = AGENT_SITES.iter().find(|site| {
        target
            .get(..site.len())
            .is_some_and(|host| host.eq_ignore_ascii_case(site))
    })?;
    let after = &target[site.len()..];
    let path = if after.starts_with('/') {
        after
            .find(|c: char| c == ')' || c.is_whitespace())
            .unwrap_or(after.len())
    } else {
        0
    };
    after[path..].starts_with(')').then(|| {
        let length = text.len() - after.len() + path + 1;
        (label, length)
    })
}

#[cfg(test)]
mod tests {
    use super::remove_agent_credits;

    #[test]
    fn credits_quoted_in_code_and_people_on_githubs_noreply_address_stay() {
        let message = "Explain trailers\r\n\r\n```\r\nCo-authored-by: Claude <noreply@anthropic.com>\r\n```\r\n    Generated with Codex\r\n- Co-authored-by: Octo Cat <noreply@github.com>\r\n* Co-authored-by: Copilot <noreply@github.com>\r\nGenerated by codex.\r\n\r\n";
        assert_eq!(
            remove_agent_credits(message),
            "Explain trailers\r\n\r\n```\r\nCo-authored-by: Claude <noreply@anthropic.com>\r\n```\r\n    Generated with Codex\r\n- Co-authored-by: Octo Cat <noreply@github.com>"
        );
        let untouched = "Generated with care\n\nCo-authored-by: Ada <ada@example.com>\n\n";
        assert_eq!(remove_agent_credits(untouched), untouched);
    }
}
