//! Client-side terminal emulation, rendering snapshots, scrollback, and selection.

use std::{
    sync::{
        Arc, Mutex, Weak,
        atomic::{AtomicUsize, Ordering},
    },
    thread,
    time::Instant,
};

use rio_vt::{
    ansi::CursorShape as RioCursorShape,
    config::colors::{AnsiColor, ColorRgb, NamedColor},
    crosswords::{
        Crosswords, CrosswordsSize, Mode,
        grid::{Dimensions, Indexed, Scroll},
        pos::{Column, Line, Pos, Side as RioSide},
        square::{ContentTag, Wide},
        style::{Style, StyleFlags},
    },
    event::{EventListener, RioEvent, WindowId, WindowSize, sync::FairMutex},
    performer::handler::Processor,
    selection::{Selection, SelectionType},
};

use crate::{
    Cell, Color, CursorShape, ModeSnapshot, SelectedText, SelectionKind, SelectionSide, TermState,
    hyperlinks,
};
#[cfg(test)]
use crate::{DEFAULT_COLS, DEFAULT_ROWS};

impl From<SelectionSide> for RioSide {
    fn from(side: SelectionSide) -> Self {
        match side {
            SelectionSide::Left => Self::Left,
            SelectionSide::Right => Self::Right,
        }
    }
}

/// Data emitted by terminal emulation.
///
/// `Input` contains protocol replies generated by the emulator (for example a
/// device-attributes response) and must be sent back to the host PTY.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) enum GridEvent {
    Wakeup,
    TitleChanged(Option<String>),
    CursorBlinkingChanged,
    Bell,
    Input(Vec<u8>),
}

/// Client-side terminal state machine.
///
/// This type accepts raw output bytes and owns all terminal grid state. It has
/// no PTY, child-process, or platform process types in its public API.
#[derive(Clone)]
pub(crate) struct GridEmulator {
    core: Arc<GridCore>,
    events: async_channel::Receiver<GridEvent>,
}

struct GridCore {
    state: FairMutex<GridState>,
    notifications: async_channel::Sender<GridEvent>,
    osc_title: Arc<Mutex<Option<String>>>,
    fallback_title: Mutex<String>,
    lifecycle: Mutex<GridLifecycle>,
    size: Arc<AtomicGridSize>,
}

struct GridState {
    term: Crosswords<GridListener>,
    parser: Processor,
}

#[derive(Default)]
struct GridLifecycle {
    exited: bool,
    exit_code: Option<i32>,
}

struct AtomicGridSize {
    cols: AtomicUsize,
    rows: AtomicUsize,
}

impl AtomicGridSize {
    fn new(cols: usize, rows: usize) -> Self {
        Self {
            cols: AtomicUsize::new(cols),
            rows: AtomicUsize::new(rows),
        }
    }

    fn store(&self, cols: usize, rows: usize) {
        self.cols.store(cols, Ordering::Relaxed);
        self.rows.store(rows, Ordering::Relaxed);
    }

    fn window_size(&self) -> WindowSize {
        GridSize {
            cols: self.cols.load(Ordering::Relaxed),
            rows: self.rows.load(Ordering::Relaxed),
        }
        .window_size()
    }
}

#[derive(Clone)]
struct GridListener {
    notifications: async_channel::Sender<GridEvent>,
    osc_title: Arc<Mutex<Option<String>>>,
    size: Arc<AtomicGridSize>,
}

impl EventListener for GridListener {
    fn send_event(&self, event: RioEvent, _window_id: WindowId) {
        match event {
            RioEvent::Title(title) => {
                *self.osc_title.lock().unwrap() = Some(title.clone());
                let _ = self
                    .notifications
                    .try_send(GridEvent::TitleChanged(Some(title)));
            }
            RioEvent::ResetTitle => {
                *self.osc_title.lock().unwrap() = None;
                let _ = self.notifications.try_send(GridEvent::TitleChanged(None));
            }
            RioEvent::CursorBlinkingChange | RioEvent::CursorBlinkingChangeOnRoute(_) => {
                let _ = self
                    .notifications
                    .try_send(GridEvent::CursorBlinkingChanged);
            }
            RioEvent::Bell => {
                let _ = self.notifications.try_send(GridEvent::Bell);
            }
            RioEvent::Render
            | RioEvent::RenderRoute(_)
            | RioEvent::TerminalDamaged(_)
            | RioEvent::PrepareRender(_)
            | RioEvent::PrepareRenderOnRoute(_, _) => {
                let _ = self.notifications.try_send(GridEvent::Wakeup);
            }
            RioEvent::PtyWrite(_, text) => {
                let text = if text == "\x1b[?62;4;6;22;52c" {
                    "\x1b[?6c".to_string()
                } else {
                    text
                };
                let _ = self
                    .notifications
                    .try_send(GridEvent::Input(text.into_bytes()));
            }
            RioEvent::ColorRequest(_, index, format) => {
                let bytes = format(query_color(index)).into_bytes();
                let _ = self.notifications.try_send(GridEvent::Input(bytes));
            }
            RioEvent::TextAreaSizeRequest(_, format) => {
                let bytes = format(self.size.window_size()).into_bytes();
                let _ = self.notifications.try_send(GridEvent::Input(bytes));
            }
            _ => {}
        }
    }
}

#[derive(Clone, Copy)]
struct GridSize {
    cols: usize,
    rows: usize,
}

impl Dimensions for GridSize {
    fn total_lines(&self) -> usize {
        self.rows
    }

    fn screen_lines(&self) -> usize {
        self.rows
    }

    fn columns(&self) -> usize {
        self.cols
    }
}

impl GridSize {
    fn window_size(self) -> WindowSize {
        WindowSize {
            rows: self.rows as u16,
            cols: self.cols as u16,
            width: 8,
            height: 17,
        }
    }
}

impl GridEmulator {
    /// Create an 80×24 emulator with 1,000 lines of scrollback.
    #[cfg(test)]
    pub fn new() -> Self {
        Self::with_size(DEFAULT_COLS, DEFAULT_ROWS)
    }

    /// Create an emulator with an explicit initial grid size.
    #[cfg(test)]
    pub fn with_size(cols: usize, rows: usize) -> Self {
        Self::with_size_and_title(cols, rows, String::new())
    }

    pub(crate) fn with_size_and_title(cols: usize, rows: usize, fallback_title: String) -> Self {
        let size = GridSize {
            cols: cols.max(2),
            rows: rows.max(2),
        };
        let (notifications, events) = async_channel::unbounded();
        let osc_title = Arc::new(Mutex::new(None));
        let atomic_size = Arc::new(AtomicGridSize::new(size.cols, size.rows));
        let listener = GridListener {
            notifications: notifications.clone(),
            osc_title: osc_title.clone(),
            size: atomic_size.clone(),
        };
        let term = Crosswords::new(
            CrosswordsSize::new(size.cols, size.rows),
            RioCursorShape::Block,
            listener,
            WindowId::from(0),
            0,
            1000,
        );
        let core = Arc::new(GridCore {
            state: FairMutex::new(GridState {
                term,
                parser: Processor::default(),
            }),
            notifications,
            osc_title,
            fallback_title: Mutex::new(fallback_title),
            lifecycle: Mutex::new(GridLifecycle::default()),
            size: atomic_size,
        });
        Self { core, events }
    }

    /// Consume raw output bytes from the host PTY.
    ///
    /// Parser state is retained across calls, so chunks may split UTF-8,
    /// control sequences, OSC hyperlinks, or synchronized updates at any byte.
    pub fn feed(&self, bytes: &[u8]) {
        if bytes.is_empty() {
            return;
        }

        let (expired_sync, wakeup, sync_deadline) = {
            let mut state = self.core.state.lock();
            let expired_sync = stop_expired_sync(&mut state);
            let GridState { term, parser } = &mut *state;
            parser.advance(term, bytes);
            let wakeup = parser.sync_bytes_count() < bytes.len();
            let sync_deadline = parser.sync_timeout().sync_timeout();
            (expired_sync, wakeup, sync_deadline)
        };

        if expired_sync {
            let _ = self.core.notifications.try_send(GridEvent::Wakeup);
        }
        if wakeup {
            let _ = self.core.notifications.try_send(GridEvent::Wakeup);
        }
        if let Some(deadline) = sync_deadline {
            schedule_sync_timeout(Arc::downgrade(&self.core), deadline);
        }
    }

    /// Return rendering-relevant emulator events.
    ///
    /// Cloned receivers compete for events. Install one draining task and fan
    /// out from there when multiple consumers are needed.
    pub fn events(&self) -> async_channel::Receiver<GridEvent> {
        self.events.clone()
    }

    /// Apply the local viewport behavior associated with user input.
    ///
    /// This scrolls to the bottom and clears any selection; the bytes
    /// themselves still belong on the host-side [`crate::PtyHandle`].
    pub fn prepare_input(&self) {
        self.prepare_input_if_changed();
    }

    pub(crate) fn prepare_input_if_changed(&self) -> bool {
        let mut state = self.core.state.lock();
        let display_offset = state.term.display_offset();
        let had_selection = state.term.selection.take().is_some();
        state.term.scroll_display(Scroll::Bottom);
        let changed = had_selection || state.term.display_offset() != display_offset;
        drop(state);
        if changed {
            let _ = self.core.notifications.try_send(GridEvent::Wakeup);
        }
        changed
    }

    pub(crate) fn resize_if_changed(&self, cols: usize, rows: usize) -> bool {
        let cols = cols.max(2);
        let rows = rows.max(2);
        let mut state = self.core.state.lock();
        if state.term.columns() == cols && state.term.screen_lines() == rows {
            return false;
        }
        state.term.resize(CrosswordsSize::new(cols, rows));
        self.core.size.store(cols, rows);
        drop(state);
        let _ = self.core.notifications.try_send(GridEvent::Wakeup);
        true
    }

    pub fn scroll(&self, lines: i32) {
        let mut state = self.core.state.lock();
        let display_offset = state.term.display_offset();
        state.term.scroll_display(Scroll::Delta(lines));
        let changed = state.term.display_offset() != display_offset;
        drop(state);
        if changed {
            let _ = self.core.notifications.try_send(GridEvent::Wakeup);
        }
    }

    /// Start or update a simple selection using zero-based visible grid coordinates.
    pub fn select(&self, start: (usize, usize), end: (usize, usize)) {
        self.select_kind(start, end, SelectionKind::Simple);
    }

    /// Start or update a selection of the requested kind.
    fn select_kind(&self, start: (usize, usize), end: (usize, usize), kind: SelectionKind) {
        let mut state = self.core.state.lock();
        let offset = state.term.display_offset() as i32;
        let point = |(row, col): (usize, usize)| {
            Pos::new(
                Line(row as i32 - offset),
                Column(col.min(state.term.columns() - 1)),
            )
        };
        let selection_type = selection_type(kind);
        let mut selection = Selection::new(selection_type, point(start), RioSide::Left);
        selection.update(point(end), RioSide::Right);
        state.term.selection = Some(selection);
        drop(state);
        let _ = self.core.notifications.try_send(GridEvent::Wakeup);
    }

    /// Start an interactive selection at an empty anchor in visible grid coordinates.
    pub fn start_selection(&self, kind: SelectionKind, point: (usize, usize), side: SelectionSide) {
        let mut state = self.core.state.lock();
        let offset = state.term.display_offset() as i32;
        let point = Pos::new(
            Line(point.0 as i32 - offset),
            Column(point.1.min(state.term.columns() - 1)),
        );
        state.term.selection = Some(Selection::new(selection_type(kind), point, side.into()));
        drop(state);
        let _ = self.core.notifications.try_send(GridEvent::Wakeup);
    }

    /// Update the existing interactive selection using visible grid coordinates.
    pub fn update_selection(&self, point: (usize, usize), side: SelectionSide) {
        let mut state = self.core.state.lock();
        let offset = state.term.display_offset() as i32;
        let point = Pos::new(
            Line(point.0 as i32 - offset),
            Column(point.1.min(state.term.columns() - 1)),
        );
        if let Some(selection) = state.term.selection.as_mut() {
            selection.update(point, side.into());
        }
        drop(state);
        let _ = self.core.notifications.try_send(GridEvent::Wakeup);
    }

    pub fn clear_selection(&self) {
        let mut state = self.core.state.lock();
        let changed = state.term.selection.take().is_some();
        drop(state);
        if changed {
            let _ = self.core.notifications.try_send(GridEvent::Wakeup);
        }
    }

    pub fn select_all(&self) {
        let mut state = self.core.state.lock();
        let mut selection = Selection::new(
            SelectionType::Simple,
            Pos::new(Line(-(state.term.history_size() as i32)), Column(0)),
            RioSide::Left,
        );
        selection.update(
            Pos::new(state.term.bottommost_line(), state.term.last_column()),
            RioSide::Right,
        );
        state.term.selection = Some(selection);
        drop(state);
        let _ = self.core.notifications.try_send(GridEvent::Wakeup);
    }

    pub fn clear(&self) {
        let mut state = self.core.state.lock();
        state.term.clear_saved_history();

        let cursor = state.term.grid.cursor.pos;
        state.term.grid.reset_region(..cursor.row);

        let line = state.term.grid[cursor.row][..Column(state.term.columns())]
            .iter()
            .copied()
            .enumerate()
            .collect::<Vec<_>>();
        for (index, cell) in line {
            state.term.grid[Line(0)][Column(index)] = cell;
        }

        state.term.grid.cursor.pos = Pos::new(Line(0), cursor.col);
        if state.term.screen_lines() > 1 {
            state.term.grid.reset_region(Line(1)..);
        }
        state.term.selection = None;
        drop(state);
        let _ = self.core.notifications.try_send(GridEvent::Wakeup);
    }

    pub fn selected_text(&self) -> Option<SelectedText> {
        let state = self.core.state.lock();
        let range = state.term.selection.as_ref()?.to_range(&state.term)?;
        let history = state.term.history_size() as i32;
        let line_number = |line: Line| (history + line.0 + 1).max(1) as usize;
        let text = state
            .term
            .selection_to_string()?
            .trim_matches('\n')
            .to_string();
        if text.is_empty() {
            return None;
        }
        Some(SelectedText {
            line_start: line_number(range.start.row),
            line_end: line_number(range.end.row),
            text,
        })
    }

    pub fn snapshot(&self) -> TermState {
        let state = self.core.state.lock();
        let cols = state.term.columns();
        let rows = state.term.screen_lines();
        let display_offset = state.term.display_offset();
        let cursor_state = state.term.cursor();
        let display_cursor_line = cursor_state.pos.row.0 + display_offset as i32;
        let cursor = if display_cursor_line >= 0 && display_cursor_line < rows as i32 {
            Some((display_cursor_line as usize, cursor_state.pos.col.0))
        } else {
            None
        };
        let selection = state
            .term
            .selection
            .as_ref()
            .and_then(|selection| selection.to_range(&state.term));
        let visible_rows = state.term.visible_rows();
        let mut cells = Vec::with_capacity(cols * rows);
        for (row, row_cells) in visible_rows.iter().enumerate() {
            for col in 0..cols {
                let pos = Pos::new(Line(row as i32 - display_offset as i32), Column(col));
                let square = row_cells[Column(col)];
                let selected = selection.is_some_and(|range| {
                    range.contains_square(
                        &Indexed {
                            pos,
                            square: &square,
                        },
                        cursor_state.pos,
                        cursor_state.content,
                    )
                });
                let (ch, text, style) = match square.content_tag() {
                    ContentTag::Codepoint => {
                        let ch = display_char(square.c());
                        let text = state.term.grid.cell_text(pos).map(display_char).collect();
                        (ch, text, state.term.grid.style_of(&square))
                    }
                    ContentTag::BgPalette => {
                        let style = Style {
                            bg: AnsiColor::Indexed(square.bg_palette_index()),
                            ..Style::default()
                        };
                        (' ', " ".to_string(), style)
                    }
                    ContentTag::BgRgb => {
                        let (r, g, b) = square.bg_rgb();
                        let style = Style {
                            bg: AnsiColor::Spec(ColorRgb { r, g, b }),
                            ..Style::default()
                        };
                        (' ', " ".to_string(), style)
                    }
                };
                cells.push(Cell {
                    ch,
                    text,
                    fg: convert_color(style.fg),
                    bg: convert_color(style.bg),
                    bold: style.flags.contains(StyleFlags::BOLD),
                    italic: style.flags.contains(StyleFlags::ITALIC),
                    underline: style.flags.intersects(StyleFlags::ALL_UNDERLINES),
                    inverse: style.flags.contains(StyleFlags::INVERSE),
                    selected,
                    wide: square.wide() == Wide::Wide,
                    wide_spacer: square.wide() == Wide::Spacer,
                });
            }
        }
        let mode = state.term.mode();
        let history_size = state.term.history_size();
        let cursor_shape = cursor_state.content;
        let cursor_blinking = state.term.blinking_cursor;
        drop(state);
        let lifecycle = self.core.lifecycle.lock().unwrap();
        TermState {
            cols,
            rows,
            cells,
            cursor,
            cursor_shape: map_cursor_shape(cursor_shape),
            cursor_blinking,
            title: self.title(),
            exited: lifecycle.exited,
            exit_code: lifecycle.exit_code,
            display_offset,
            history_size,
            mode: ModeSnapshot {
                mouse_click: mode.contains(Mode::MOUSE_REPORT_CLICK),
                mouse_motion: mode.contains(Mode::MOUSE_MOTION),
                mouse_drag: mode.contains(Mode::MOUSE_DRAG),
                sgr_mouse: mode.contains(Mode::SGR_MOUSE),
                utf8_mouse: mode.contains(Mode::UTF8_MOUSE),
                alt_screen: mode.contains(Mode::ALT_SCREEN),
                alternate_scroll: mode.contains(Mode::ALTERNATE_SCROLL),
                bracketed_paste: mode.contains(Mode::BRACKETED_PASTE),
                app_cursor: mode.contains(Mode::APP_CURSOR),
                focus_in_out: mode.contains(Mode::FOCUS_IN_OUT),
            },
        }
    }

    pub fn hyperlink_at(&self, row: usize, col: usize) -> Option<crate::HyperlinkMatch> {
        let state = self.core.state.lock();
        (row < state.term.screen_lines() && col < state.term.columns())
            .then(|| hyperlinks::find(&state.term, row, col))
            .flatten()
    }

    /// Set the non-OSC title used when the emulated terminal has no title.
    pub fn set_fallback_title(&self, title: impl Into<String>) {
        *self.core.fallback_title.lock().unwrap() = title.into();
    }

    pub fn title(&self) -> String {
        self.core
            .osc_title
            .lock()
            .unwrap()
            .clone()
            .unwrap_or_else(|| self.core.fallback_title.lock().unwrap().clone())
    }

    /// Return the title set by terminal output, excluding the fallback title.
    pub fn osc_title(&self) -> Option<String> {
        self.core.osc_title.lock().unwrap().clone()
    }

    /// Apply a host-side exit data event to this client-side snapshot.
    pub fn set_exited(&self, exit_code: Option<i32>) {
        let mut lifecycle = self.core.lifecycle.lock().unwrap();
        lifecycle.exited = true;
        lifecycle.exit_code = exit_code;
    }
}

fn stop_expired_sync(state: &mut GridState) -> bool {
    let expired = state
        .parser
        .sync_timeout()
        .sync_timeout()
        .is_some_and(|deadline| deadline <= Instant::now());
    if expired {
        let GridState { term, parser } = state;
        parser.stop_sync(term);
    }
    expired
}

fn schedule_sync_timeout(core: Weak<GridCore>, deadline: Instant) {
    let _timer = thread::Builder::new()
        .name("tcode-terminal-sync-timeout".into())
        .spawn(move || {
            thread::sleep(deadline.saturating_duration_since(Instant::now()));
            let Some(core) = core.upgrade() else {
                return;
            };
            let expired = {
                let mut state = core.state.lock();
                stop_expired_sync(&mut state)
            };
            if expired {
                let _ = core.notifications.try_send(GridEvent::Wakeup);
            }
        });
}

fn selection_type(kind: SelectionKind) -> SelectionType {
    match kind {
        SelectionKind::Simple => SelectionType::Simple,
        SelectionKind::Semantic => SelectionType::Semantic,
        SelectionKind::Lines => SelectionType::Lines,
    }
}

fn map_cursor_shape(shape: RioCursorShape) -> CursorShape {
    match shape {
        RioCursorShape::Block => CursorShape::Block,
        RioCursorShape::Underline => CursorShape::Underline,
        RioCursorShape::Beam => CursorShape::Bar,
        RioCursorShape::Hidden => CursorShape::Hidden,
    }
}

fn query_color(index: usize) -> ColorRgb {
    const ANSI: [u32; 16] = [
        0x1f2329, 0xe45649, 0x50a14f, 0xc18401, 0x4078f2, 0xa626a4, 0x0184bc, 0xabb2bf, 0x5c6370,
        0xff616e, 0x7bc275, 0xe5c07b, 0x61afef, 0xc678dd, 0x56b6c2, 0xffffff,
    ];
    let value = match index {
        0..=15 => ANSI[index],
        16..=231 => {
            let n = (index - 16) as u32;
            let component = |value: u32| if value == 0 { 0 } else { 55 + value * 40 };
            (component(n / 36) << 16) | (component((n % 36) / 6) << 8) | component(n % 6)
        }
        232..=255 => {
            let gray = 8 + (index - 232) as u32 * 10;
            (gray << 16) | (gray << 8) | gray
        }
        index if index == NamedColor::Background as usize => 0xffffff,
        index if index == NamedColor::Cursor as usize => 0x1f2329,
        _ => 0x1f2329,
    };
    ColorRgb {
        r: (value >> 16) as u8,
        g: (value >> 8) as u8,
        b: value as u8,
    }
}

fn display_char(ch: char) -> char {
    if ch == '\0' { ' ' } else { ch }
}

fn convert_color(color: AnsiColor) -> Color {
    match color {
        AnsiColor::Spec(rgb) => Color::Rgb(rgb.r, rgb.g, rgb.b),
        AnsiColor::Indexed(index) => Color::Indexed(index),
        AnsiColor::Named(named) => match named {
            NamedColor::Foreground | NamedColor::LightForeground | NamedColor::DimForeground => {
                Color::DefaultForeground
            }
            NamedColor::Background => Color::DefaultBackground,
            NamedColor::Cursor => Color::DefaultForeground,
            NamedColor::DimBlack => Color::Indexed(0),
            NamedColor::DimRed => Color::Indexed(1),
            NamedColor::DimGreen => Color::Indexed(2),
            NamedColor::DimYellow => Color::Indexed(3),
            NamedColor::DimBlue => Color::Indexed(4),
            NamedColor::DimMagenta => Color::Indexed(5),
            NamedColor::DimCyan => Color::Indexed(6),
            NamedColor::DimWhite => Color::Indexed(7),
            named => Color::Indexed(named as u8),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scripted_byte_boundary_matches_combined_feed_snapshot() {
        let script = concat!(
            "plain\r\n",
            "\u{1b}[1;31mred\u{1b}[0m ",
            "中文e\u{301}\r\n",
            "\u{1b}]8;;https://example.com/target\u{1b}\\link",
            "\u{1b}]8;;\u{1b}\\",
            "\u{1b}]2;scripted title\u{7}",
        )
        .as_bytes();

        let combined = GridEmulator::new();
        combined.feed(script);

        let chunked = GridEmulator::new();
        for chunk in script.chunks(3) {
            chunked.feed(chunk);
        }

        assert_eq!(chunked.snapshot(), combined.snapshot());
        let state = chunked.snapshot();
        let link =
            state.cells.iter().enumerate().find_map(|(index, _)| {
                chunked.hyperlink_at(index / state.cols, index % state.cols)
            });
        assert_eq!(link.unwrap().url, "https://example.com/target");
    }

    #[test]
    fn title_bell_and_protocol_reply_are_data_events() {
        let emulator = GridEmulator::new();
        let events = emulator.events();
        emulator.feed(b"\x07\x1b]2;client title\x07\x1b[c");

        let emitted = std::iter::from_fn(|| events.try_recv().ok()).collect::<Vec<_>>();
        assert!(emitted.contains(&GridEvent::Bell));
        assert!(emitted.contains(&GridEvent::TitleChanged(Some("client title".to_string()))));
        assert!(emitted.contains(&GridEvent::Input(b"\x1b[?6c".to_vec())));
    }

    #[test]
    fn maps_all_rio_cursor_shapes() {
        use rio_vt::ansi::CursorShape as Shape;
        assert_eq!(map_cursor_shape(Shape::Block), CursorShape::Block);
        assert_eq!(map_cursor_shape(Shape::Underline), CursorShape::Underline);
        assert_eq!(map_cursor_shape(Shape::Beam), CursorShape::Bar);
        assert_eq!(map_cursor_shape(Shape::Hidden), CursorShape::Hidden);
    }
}
